//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahorros.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Cuentas
    {
        public int idCuenta { get; set; }
        public string DUI { get; set; }
        public string nombreCuenta { get; set; }
        public Nullable<decimal> entrada { get; set; }
        public Nullable<decimal> salida { get; set; }
        public Nullable<decimal> saldoActual { get; set; }
    
        public virtual tb_Usuarios tb_Usuarios { get; set; }
    }
}
